[package]
name = "for-tuple"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
thiserror = "1"
syn = { version = "2", features = ["extra-traits", "parsing"] }
proc-macro2 = "1"
quote = "1"
